[package]
name = "my-service-bus-tcp-shared"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-service-bus-shared = { branch = "main", git = "https://github.com/MyJetTools/my-service-bus-shared.git" }

tokio = { version = "*", features = ["full"] }
tokio-util = "*"
async-trait = "*"
