name: Test it

on:
  push:
    branches: [ 1.*, main ]
  pull_request:
    branches: [ 1.*, main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test Build      
        run: |
          cargo test
